In [1]:
import pandas as pd
import os
os.chdir(r'C:\Users\cyrus\Case_Study_Coursera\cleaning data')
for f in os.listdir(r'C:\Users\cyrus\Case_Study_Coursera\cleaning data'):
	print(f)
df202004 = pd.read_csv("202004-divvy-tripdata.csv")
df202005 = pd.read_csv("202005-divvy-tripdata.csv")
df202006 = pd.read_csv("202006-divvy-tripdata.csv")
df202007 = pd.read_csv("202007-divvy-tripdata.csv")
df202008 = pd.read_csv("202008-divvy-tripdata.csv")
df202009 = pd.read_csv("202009-divvy-tripdata.csv")
df202010 = pd.read_csv("202010-divvy-tripdata.csv")
df202011 = pd.read_csv("202011-divvy-tripdata.csv")
df202012 = pd.read_csv("202012-divvy-tripdata.csv")
df202101 = pd.read_csv("202101-divvy-tripdata.csv")
df202102 = pd.read_csv("202102-divvy-tripdata.csv")
df202103 = pd.read_csv("202103-divvy-tripdata.csv")
df = [df202004,df202005,df202006,df202007,df202008,df202009,df202010,df202011,df202012,df202101,df202102,df202103]
df = pd.concat(df)

.ipynb_checkpoints
202004-divvy-tripdata.csv
202005-divvy-tripdata.csv
202006-divvy-tripdata.csv
202007-divvy-tripdata.csv
202008-divvy-tripdata.csv
202009-divvy-tripdata.csv
202010-divvy-tripdata.csv
202011-divvy-tripdata.csv
202012-divvy-tripdata.csv
202101-divvy-tripdata.csv
202102-divvy-tripdata.csv
202103-divvy-tripdata.csv
cleaned_data.csv
Untitled.ipynb

C:\Users\cyrus\AppData\Local\Temp/ipykernel_16632/2771798168.py:9: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df202007 = pd.read_csv("202007-divvy-tripdata.csv")

In [2]:
print(df.info())
print(df.describe)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3451081 entries, 0 to 226713
Data columns (total 18 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
 13  ride_length         object
 14  week_day            float64
 15  start_lat+lng       object
 16  end_lat+lng         float64
 17  trip_length         object
dtypes: float64(6), object(12)
memory usage: 500.3+ MB
None
<bound method NDFrame.describe of                  ride_id  rideable_type       started_at         ended_at  \
0       27AD306C119C6158    docked_bike  18/4/2020 10:22  18/4/2020 11:15
1       FC8BC2E2D54F35ED    docked_bike   7/4/2020 12:22   7/4/2020 13:38
2       9EC5648678DE06E6    docked_bike  15/4/2020 10:30  15/4/2020 10:35
3       B0EEA4FBCF6E26A3    docked_bike   18/4/2020 2:59   18/4/2020 3:07
4       5F2A5CC2510F0396    docked_bike   4/4/2020 10:52   4/4/2020 11:08
...                  ...            ...              ...              ...
226709  081549DEA616CA22  electric_bike   14/3/2021 1:59   14/3/2021 3:13
226710  BBBEB8D51AAD40DA   classic_bike   2/3/2021 11:35   2/3/2021 11:43
226711  637FF754DA0BD9E1   classic_bike   9/3/2021 11:07   9/3/2021 11:49
226712  F8F43A0B978A7A35   classic_bike   1/3/2021 18:11   1/3/2021 18:18
226713  3AE64EA5BF43CF72  electric_bike  26/3/2021 17:58  26/3/2021 18:06

                start_station_name start_station_id  \
0             Rush St & Hubbard St            125.0
1         Ogden Ave & Roosevelt Rd            434.0
2            LaSalle Dr & Huron St            627.0
3          Leavitt St & Archer Ave              9.0
4           Clark St & Lincoln Ave            141.0
...                            ...              ...
226709  Larrabee St & Armitage Ave     TA1309000006
226710    Kingsbury St & Kinzie St     KA1503000043
226711       Michigan Ave & Oak St            13042
226712    Kingsbury St & Kinzie St     KA1503000043
226713                         NaN              NaN

                      end_station_name end_station_id  start_lat  start_lng  \
0           Sheridan Rd & Lawrence Ave          323.0  41.890200 -87.626200
1          Western Ave & Congress Pkwy          382.0  41.866500 -87.684700
2            Larrabee St & Division St          359.0  41.894900 -87.632300
3              Leavitt St & Archer Ave            9.0  41.828800 -87.680600
4       Southport Ave & Wrightwood Ave          190.0  41.915700 -87.634600
...                                ...            ...        ...        ...
226709            New St & Illinois St   TA1306000013  41.918129 -87.643749
226710            New St & Illinois St   TA1306000013  41.889177 -87.638506
226711           Clark St & Berwyn Ave   KA1504000146  41.900960 -87.623777
226712            New St & Illinois St   TA1306000013  41.889177 -87.638506
226713            New St & Illinois St   TA1306000013  41.880000 -87.630000

          end_lat    end_lng member_casual ride_length  week_day  \
0       41.969500 -87.654700        casual     0:53:00       7.0
1       41.874700 -87.686400        casual     1:16:00       3.0
2       41.903500 -87.643400        casual     0:05:00       4.0
3       41.828800 -87.680600        casual     0:08:00       7.0
4       41.928800 -87.663900        casual     0:16:00       7.0
...           ...        ...           ...         ...       ...
226709  41.890808 -87.618779        member     1:14:00       1.0
226710  41.890847 -87.618617        member     0:08:00       3.0
226711  41.977997 -87.668047        member     0:42:00       3.0
226712  41.890847 -87.618617        member     0:07:00       2.0
226713  41.890818 -87.619540        member     0:08:00       6.0

       start_lat+lng  end_lat+lng trip_length
0                NaN          NaN         NaN
1                NaN          NaN         NaN
2                NaN          NaN         NaN
3                NaN          NaN         NaN
4                NaN          NaN         NaN
...              ...          ...         ...
226709           NaN          NaN         NaN
226710           NaN          NaN         NaN
226711           NaN          NaN         NaN
226712           NaN          NaN         NaN
226713           NaN          NaN         NaN

[3451081 rows x 18 columns]>

In [3]:
del df['start_lat+lng']
del df['end_lat+lng']
del df['trip_length']

In [4]:
clean_df = df.dropna(axis = 0, how ='any') 
print("Old data frame length:", len(df), "\nNew data frame length:",  
       len(clean_df), "\nNumber of rows with at least 1 NA value:", 
       (len(df)-len(clean_df)))

clean_df.head

Old data frame length: 3451081
New data frame length: 2112630
Number of rows with at least 1 NA value: 1338451

<bound method NDFrame.head of                  ride_id  rideable_type       started_at         ended_at  \
0       27AD306C119C6158    docked_bike  18/4/2020 10:22  18/4/2020 11:15
1       FC8BC2E2D54F35ED    docked_bike   7/4/2020 12:22   7/4/2020 13:38
2       9EC5648678DE06E6    docked_bike  15/4/2020 10:30  15/4/2020 10:35
3       B0EEA4FBCF6E26A3    docked_bike   18/4/2020 2:59   18/4/2020 3:07
4       5F2A5CC2510F0396    docked_bike   4/4/2020 10:52   4/4/2020 11:08
...                  ...            ...              ...              ...
226708  893CB76A502E4653   classic_bike  29/3/2021 16:05  29/3/2021 16:12
226709  081549DEA616CA22  electric_bike   14/3/2021 1:59   14/3/2021 3:13
226710  BBBEB8D51AAD40DA   classic_bike   2/3/2021 11:35   2/3/2021 11:43
226711  637FF754DA0BD9E1   classic_bike   9/3/2021 11:07   9/3/2021 11:49
226712  F8F43A0B978A7A35   classic_bike   1/3/2021 18:11   1/3/2021 18:18

                start_station_name start_station_id  \
0             Rush St & Hubbard St            125.0
1         Ogden Ave & Roosevelt Rd            434.0
2            LaSalle Dr & Huron St            627.0
3          Leavitt St & Archer Ave              9.0
4           Clark St & Lincoln Ave            141.0
...                            ...              ...
226708       Clark St & Leland Ave     TA1309000014
226709  Larrabee St & Armitage Ave     TA1309000006
226710    Kingsbury St & Kinzie St     KA1503000043
226711       Michigan Ave & Oak St            13042
226712    Kingsbury St & Kinzie St     KA1503000043

                      end_station_name end_station_id  start_lat  start_lng  \
0           Sheridan Rd & Lawrence Ave          323.0  41.890200 -87.626200
1          Western Ave & Congress Pkwy          382.0  41.866500 -87.684700
2            Larrabee St & Division St          359.0  41.894900 -87.632300
3              Leavitt St & Archer Ave            9.0  41.828800 -87.680600
4       Southport Ave & Wrightwood Ave          190.0  41.915700 -87.634600
...                                ...            ...        ...        ...
226708           Clark St & Berwyn Ave   KA1504000146  41.967096 -87.667429
226709            New St & Illinois St   TA1306000013  41.918129 -87.643749
226710            New St & Illinois St   TA1306000013  41.889177 -87.638506
226711           Clark St & Berwyn Ave   KA1504000146  41.900960 -87.623777
226712            New St & Illinois St   TA1306000013  41.889177 -87.638506

          end_lat    end_lng member_casual ride_length  week_day
0       41.969500 -87.654700        casual     0:53:00       7.0
1       41.874700 -87.686400        casual     1:16:00       3.0
2       41.903500 -87.643400        casual     0:05:00       4.0
3       41.828800 -87.680600        casual     0:08:00       7.0
4       41.928800 -87.663900        casual     0:16:00       7.0
...           ...        ...           ...         ...       ...
226708  41.977997 -87.668047        member     0:07:00       2.0
226709  41.890808 -87.618779        member     1:14:00       1.0
226710  41.890847 -87.618617        member     0:08:00       3.0
226711  41.977997 -87.668047        member     0:42:00       3.0
226712  41.890847 -87.618617        member     0:07:00       2.0

[2112630 rows x 15 columns]>

In [5]:
day = {
    1:"Sunday",
    2:"Monday",
    3:"Tuesday",
    4:"Wednesday",
    5:"Thursday",
    6:"Friday",
    7:"Saturday"
}
clean_df["week_day"].replace(day, inplace=True)
clean_df.head

C:\Users\cyrus\AppData\Local\Temp/ipykernel_16632/963155591.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["week_day"].replace(day, inplace=True)

<bound method NDFrame.head of                  ride_id  rideable_type       started_at         ended_at  \
0       27AD306C119C6158    docked_bike  18/4/2020 10:22  18/4/2020 11:15
1       FC8BC2E2D54F35ED    docked_bike   7/4/2020 12:22   7/4/2020 13:38
2       9EC5648678DE06E6    docked_bike  15/4/2020 10:30  15/4/2020 10:35
3       B0EEA4FBCF6E26A3    docked_bike   18/4/2020 2:59   18/4/2020 3:07
4       5F2A5CC2510F0396    docked_bike   4/4/2020 10:52   4/4/2020 11:08
...                  ...            ...              ...              ...
226708  893CB76A502E4653   classic_bike  29/3/2021 16:05  29/3/2021 16:12
226709  081549DEA616CA22  electric_bike   14/3/2021 1:59   14/3/2021 3:13
226710  BBBEB8D51AAD40DA   classic_bike   2/3/2021 11:35   2/3/2021 11:43
226711  637FF754DA0BD9E1   classic_bike   9/3/2021 11:07   9/3/2021 11:49
226712  F8F43A0B978A7A35   classic_bike   1/3/2021 18:11   1/3/2021 18:18

                start_station_name start_station_id  \
0             Rush St & Hubbard St            125.0
1         Ogden Ave & Roosevelt Rd            434.0
2            LaSalle Dr & Huron St            627.0
3          Leavitt St & Archer Ave              9.0
4           Clark St & Lincoln Ave            141.0
...                            ...              ...
226708       Clark St & Leland Ave     TA1309000014
226709  Larrabee St & Armitage Ave     TA1309000006
226710    Kingsbury St & Kinzie St     KA1503000043
226711       Michigan Ave & Oak St            13042
226712    Kingsbury St & Kinzie St     KA1503000043

                      end_station_name end_station_id  start_lat  start_lng  \
0           Sheridan Rd & Lawrence Ave          323.0  41.890200 -87.626200
1          Western Ave & Congress Pkwy          382.0  41.866500 -87.684700
2            Larrabee St & Division St          359.0  41.894900 -87.632300
3              Leavitt St & Archer Ave            9.0  41.828800 -87.680600
4       Southport Ave & Wrightwood Ave          190.0  41.915700 -87.634600
...                                ...            ...        ...        ...
226708           Clark St & Berwyn Ave   KA1504000146  41.967096 -87.667429
226709            New St & Illinois St   TA1306000013  41.918129 -87.643749
226710            New St & Illinois St   TA1306000013  41.889177 -87.638506
226711           Clark St & Berwyn Ave   KA1504000146  41.900960 -87.623777
226712            New St & Illinois St   TA1306000013  41.889177 -87.638506

          end_lat    end_lng member_casual ride_length   week_day
0       41.969500 -87.654700        casual     0:53:00   Saturday
1       41.874700 -87.686400        casual     1:16:00    Tuesday
2       41.903500 -87.643400        casual     0:05:00  Wednesday
3       41.828800 -87.680600        casual     0:08:00   Saturday
4       41.928800 -87.663900        casual     0:16:00   Saturday
...           ...        ...           ...         ...        ...
226708  41.977997 -87.668047        member     0:07:00     Monday
226709  41.890808 -87.618779        member     1:14:00     Sunday
226710  41.890847 -87.618617        member     0:08:00    Tuesday
226711  41.977997 -87.668047        member     0:42:00    Tuesday
226712  41.890847 -87.618617        member     0:07:00     Monday

[2112630 rows x 15 columns]>

In [6]:
clean_df.to_csv("cleaned_data.csv")